### ISSUE TITLE
RuntimeError ITK only supports orthonormal direction cosines.  No orthonormal definition found!

### ISSUE THREAD

**Issue by fahadahmedkhokhar** [Svdvoort/prognosais_examples#1]
I am running the code with example_pipeline.py with given 1p19q dataset. I am facing this error while running the code. 

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:2016:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by Svdvoort** [comment]
Hi,

prognosais is actively developed anymore and the code is by now quite outdated compared to the packages it relies. Python 3.7, on which prognsais is based, is also end of life. So it's probably better to change to a different package than prognosais. 

However, that being said I can try to help you a bit. The package itself will not be upgraded anymore however. Probably your SimpleITK version is higher than what prognosais was developed for. It should work with SimpleITK version 2.0.2, which you can install by running: `pip install SimpleITK==2.0.2` and then try rerunning the pipeline.

In general I would suggest you switch to something else such as [monai](https://monai.io/)

**Comment by fahadahmedkhokhar** [comment]
Hi, can you please provide me the requirement.txt file so  that I can make the environment accordingly.
________________________________

**Comment by Svdvoort** [comment]
These requirements should work although it is an older version of prognosais: 

```text
absl-py==0.12.0
astunparse==1.6.3
cachetools==4.2.2
certifi==2020.12.5
chardet==4.0.0
cycler==0.10.0
flatbuffers==1.12
gast==0.3.3
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.32.0
gviz-api==1.9.0
h5py==2.10.0
idna==2.10
importlib-metadata==4.0.1
joblib==1.0.1
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
llvmlite==0.35.0
Markdown==3.3.4
matplotlib==3.4.2
natsort==7.1.1
numba==0.52.0
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
pandas==1.2.4
Pillow==8.2.0
prognosais==0.2.7
protobuf==3.17.0
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-learn==0.24.2
scipy==1.6.3
SimpleITK==2.0.2
six==1.15.0
slurmpie==0.4.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-profile==2.4.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-addons==0.13.0
tensorflow-estimator==2.4.0
tensorflow-io==0.17.1
termcolor==1.1.0
threadpoolctl==2.1.0
typeguard==2.12.0
typing-extensions==3.7.4.3
urllib3==1.26.4
Werkzeug==2.0.1
wrapt==1.12.1
zipp==3.4.1
```

Once again though, the Python version (and thus several of these packages) are no longer maintained so also contain some known security concerns.

**Comment by Svdvoort** [comment]
Closed, discussion is now taking place [here](https://github.com/Svdvoort/PrognosAIs_glioma/issues/7).
